extends RefCounted

static func missions() -> Array:
	return [
		{"day":1,"title":"A favor for a ghost","place":"MARA'S DINER","p":Vector3(-12,0,18),"speaker":"MARA · former dispatcher","text":"Your brother owed me a breakfast. Three years late, and now you show up wearing his jacket.\n\nEli called last night. Alive. He said: if I disappear again, give Alex the envelope. The man in the photograph is Deputy Mayor Vale. The woman is my daughter, June. She vanished the night of the harbor fire.\n\nTake the envelope to the old phone booth. Someone there still answers to a name.","goal":"Meet Mara outside the diner.","kind":"talk"},
		{"day":1,"title":"The voice on the line","place":"OLD TELEPHONE","p":Vector3(68,0,12),"speaker":"ELI · your missing brother","text":"Alex? Don't speak my name. I listened to your birthday messages. All of them.\n\nThe harbor fire wasn't an accident. I drove the truck that carried the fuel. I thought it was a repossession job. That's why I stayed gone.\n\nThere's a recorder in my old garage. Take the blue car. The keys are still where Dad hid them. And Alex ... don't forgive me yet.","goal":"Find the telephone on Mercer Avenue.","kind":"talk"},
		{"day":1,"title":"What he left behind","place":"ELI'S GARAGE","p":Vector3(148,0,12),"speaker":"RECORDER · three years earlier","text":"VALE: Vacant properties don't make headlines.\nELI: People are living there.\nVALE: Then make sure they're out.\n\nA second voice interrupts. June. 'I'm recording this. You don't get to buy another silence.'\n\nAt the bottom of the locker: a hospital bracelet dated yesterday. June might be alive. The evidence is marked for Saint Orin's clinic.","goal":"Collect the recorder at Eli's garage.","kind":"collect"},
		{"day":2,"title":"The woman without a name","place":"SAINT ORIN CLINIC","p":Vector3(12,0,-68),"speaker":"DR. IMANI","text":"June survived. Her mother didn't know because June asked me to keep her dead. A dead witness can't be subpoenaed, bought, or followed.\n\nShe's been building a case. Someone inside the redevelopment company finally agreed to talk. A bookkeeper named Tomas.\n\nBefore I tell you where she went, tell me: did Mara send you, or did Eli?","goal":"Ask Dr. Imani about the bracelet.","kind":"talk","choice":["Tell her everything. Mara deserves the truth.","Protect Eli. Say you came alone."],"responses":["IMANI: Honesty is expensive here. I'll trust you. June is at the riverside shelter. Take her this medicine.","IMANI: You hesitate just like your brother. I'll help anyway. June is at the riverside shelter. Take this medicine."]},
		{"day":2,"title":"A daughter, not a witness","place":"RIVERSIDE SHELTER","p":Vector3(-92,0,-68),"speaker":"JUNE","text":"Mum thinks she's burying me every morning. Do you know what that does to someone? I do. I let it happen.\n\nI was going to expose Vale. Then Tomas showed me the evacuation list. The company knew precisely who would still be inside. It wasn't just a property deal. Someone was erasing a neighborhood that voted against him.\n\nTomas is waiting at the freight yard. If we miss him, this becomes another rumor.","goal":"Deliver the medicine to June.","kind":"deliver"},
		{"day":2,"title":"A name on every door","place":"FREIGHT YARD","p":Vector3(-148,0,-148),"speaker":"TOMAS · bookkeeper","text":"Forty-one addresses. Eight lives. I reduced them to a column called clearance costs. I told myself numbers weren't people.\n\nHere are the signed orders. Vale isn't the top of the chain. His donor, Soren Kade, owns the company and half the patrol contracts.\n\nA security car is coming. Take the ledger to the underpass. Don't lead them to June.","goal":"Collect Tomas's ledger at the freight yard.","kind":"collect","heat":65},
		{"day":3,"title":"Lose the tail","place":"CANAL UNDERPASS","p":Vector3(12,0,148),"speaker":"ELI · over the radio","text":"You lost them. I used this underpass the night of the fire. I heard someone in the back of the truck and kept driving.\n\nIt was June. She jumped before the bridge. I didn't stop.\n\nI want to testify. But first there's something you need to see at the memorial. I can't ask you to trust me until you know whose name is there.","goal":"Escape pursuit, then reach the canal underpass.","kind":"escape"},
		{"day":3,"title":"Eight empty chairs","place":"HARBOR MEMORIAL","p":Vector3(92,0,148),"speaker":"ALEX · your voice","text":"Eight names cut into limestone. One is Daniel Reyes. Dad.\n\nEli told us Dad died driving home. It was easier than admitting he'd sent him to the harbor to help people get out.\n\nBetween the candles is a photograph. Dad and Eli, grinning beside the blue car. On the back: 'Whatever happens, bring each other home.'\n\nYou call June. This time you tell her everything.","goal":"Read the names at the harbor memorial.","kind":"collect"},
		{"day":3,"title":"The price of daylight","place":"NORTHLINE NEWS","p":Vector3(148,0,92),"speaker":"RHEA · investigative reporter","text":"A tape can be edited. A ledger can be planted. A witness can be frightened. Put all three in front of a judge and they become harder to erase.\n\nBut a leak today could warn the city before Kade clears another block. The tenants at Birch Court are still there.\n\nWe can publish the documents now, or keep the case quiet while you get them out.","goal":"Bring the evidence to reporter Rhea.","kind":"talk","choice":["Warn the tenants now. People come first.","Keep the evidence sealed for court."],"responses":["RHEA: I'll put out a warning without naming the witnesses. You're choosing people over a perfect case. So am I.","RHEA: I'll protect the originals. Get to Birch Court. Evidence won't matter if we lose the people it belongs to."]},
		{"day":4,"title":"No one gets left","place":"BIRCH COURT","p":Vector3(-68,0,92),"speaker":"MRS. ORTIZ · tenant organizer","text":"They shut off the lifts this morning. Then the water. Then a man offered me a taxi voucher to leave forty years behind.\n\nWe got everybody down the stairs. Except Mr. Bell's records. He wouldn't leave without his wife's voice. So I carried both.\n\nTake these names to the shelter. Make sure nobody disappears into a spreadsheet again.","goal":"Help the Birch Court evacuation.","kind":"deliver"},
		{"day":4,"title":"A place at the table","place":"RIVERSIDE SHELTER","p":Vector3(-92,0,-68),"speaker":"MARA","text":"June walked through the door ten minutes ago. I slapped her. Then I held her so hard she complained.\n\nThank you for bringing my girl back. Now bring your brother back. Not because he deserves it. Because he can still do something right.\n\nJune found the payment server. A maintenance key is at the parking office. Kade's people have it watched.","goal":"Deliver the tenant list to the shelter.","kind":"deliver"},
		{"day":4,"title":"Borrowed access","place":"PARKING OFFICE","p":Vector3(-148,0,12),"speaker":"JUNE · encrypted call","text":"That's the maintenance key. It opens the records terminal beside Kade's tower.\n\nHe bought judges through a charity called Second Dawn. Nice name for a business that burned the first one.\n\nOnce you copy the payments, they'll know. Plan your way out before you touch the terminal.","goal":"Retrieve the maintenance key.","kind":"collect"},
		{"day":5,"title":"Follow the money","place":"KADE RECORDS","p":Vector3(-12,0,-148),"speaker":"SYSTEM · payment archive","text":"ARCHIVE COPIED.\n\nOne payment repeats every month. Not to Vale. Not to a judge. To Eli Reyes.\n\nYour phone rings before you can breathe.\n\nELI: It paid for June's treatment. That's how he kept me quiet. Every month I told myself one more payment and she'd be safe. Every month he owned me again.\n\nThe police band interrupts. They have your location.","goal":"Copy the payment archive at Kade Records.","kind":"collect","heat":95},
		{"day":5,"title":"The long way home","place":"SOUTH SAFEHOUSE","p":Vector3(-148,0,148),"speaker":"ELI","text":"I'm here. No more phone calls. No more disappearing.\n\nI signed a statement. Every delivery, every payment, every time I looked away. Your copy is on the table.\n\nI won't ask you to save me from prison. Just don't let Kade make you into someone who can live with what I did.","goal":"Lose pursuit and meet Eli at the safehouse.","kind":"escape"},
		{"day":5,"title":"What justice costs","place":"COURTHOUSE STEPS","p":Vector3(92,0,-68),"speaker":"DETECTIVE SEN","text":"Kade offered me a promotion to lose your file. I asked for it in writing. He laughed.\n\nWe have enough to move, if Eli testifies in person. The hearing is tomorrow. Until then, keep him somewhere Kade won't expect.\n\nOne more decision. Give me the archive, or give Rhea a duplicate too. Public pressure helps. It also makes it harder to protect the witnesses.","goal":"Deliver Eli's statement to Detective Sen.","kind":"talk","choice":["Trust Sen and send Rhea a duplicate.","Keep one protected chain of evidence."],"responses":["SEN: Then everybody watches tomorrow. Let's make sure there's something to see.","SEN: I'll log every page myself. We do this carefully. We do it right."]},
		{"day":6,"title":"The last quiet morning","place":"MARA'S DINER","p":Vector3(-12,0,18),"speaker":"ELI","text":"Mara made me pay for that breakfast. Three years of interest.\n\nRemember racing bicycles down Mercer? You always said the city ended at the bridge. I believed you until I was seventeen.\n\nWhen this is over, go past it. Promise me.\n\nJune calls. Kade's guards are outside the courthouse. Sen wants us to take the river route. Your car is ready.","goal":"Meet Eli before the hearing.","kind":"talk","heat":80},
		{"day":6,"title":"Bring each other home","place":"COURTHOUSE STEPS","p":Vector3(92,0,-68),"speaker":"DETECTIVE SEN","text":"You made it. Eli's inside. June is already on the stand.\n\nKade is trying to leave by the waterfront. We have a warrant but he's cutting the communications feed. The relay at the old telephone can restore it.\n\nStay out of his way. You're a witness, Alex. Give us the signal and let us do our job.","goal":"Lose the pursuers and get Eli to court.","kind":"escape"},
		{"day":6,"title":"A city speaks","place":"OLD TELEPHONE","p":Vector3(68,0,12),"speaker":"RHEA · live broadcast","text":"The feed is back. The city can hear June.\n\nJUNE: My name is June Salcedo. I am not one of the eight people you killed. I'm the one you missed.\n\nTraffic stops at the bridge. Sen's voice comes over the radio: 'Soren Kade, step out of the vehicle.'\n\nNobody cheers at first. The city has forgotten how relief is supposed to sound.","goal":"Restore the courthouse communications relay.","kind":"collect"},
		{"day":7,"title":"What we keep","place":"HARBOR MEMORIAL","p":Vector3(92,0,148),"speaker":"ELI · a letter from custody","text":"I pleaded guilty. Sen says the testimony matters. I hope she's right, but it doesn't change the names on the wall.\n\nMara sends breakfast when she visits. June sends books with the endings torn out. She says I have to earn those.\n\nDad's car is yours. So is the road.\n\nYou stand at the memorial until the morning traffic starts. There is one thing left to decide.","goal":"Return to the memorial after the hearing.","kind":"talk","choice":["Keep Eli's letter. Visit him when you can.","Leave the letter. Begin your own life."],"responses":["You fold the letter into Dad's jacket. Forgiveness isn't a verdict. It's a road you can choose to walk, one difficult mile at a time.","You leave the letter under the photograph. Love doesn't require you to carry every consequence. For the first time, the road belongs to you."]}
	]
