import {db,bucket,identity} from '../../../lib/store';
export async function GET(){try{const {user,owner,contributor}=await identity();const events=(await db().prepare('SELECT * FROM events ORDER BY date DESC').all()).results;const photos=(await db().prepare('SELECT id,event,label FROM photos').all()).results;const orders=user?(await db().prepare(owner?'SELECT * FROM orders ORDER BY created DESC':'SELECT * FROM orders WHERE user=? ORDER BY created DESC').bind(...(owner?[]:[user.userId])).all()).results:[];const members=owner?(await db().prepare('SELECT * FROM members').all()).results:[];return Response.json({events,photos,orders,members,owner,contributor,email:user?.email});}catch(e){console.error(e);return Response.json({error:'The store is unavailable. Please try again.'},{status:503});}}
export async function POST(req:Request){try{const url=new URL(req.url);if(req.headers.get('origin')!==url.origin)return Response.json({error:'Invalid request'},{status:403});const {user,owner,contributor}=await identity();if(!user)return Response.json({error:'Please sign in first.'},{status:401});const f=await req.formData();const action=f.get('action');const id=crypto.randomUUID();if(action==='event'&&owner){const title=String(f.get('title')||'').trim();const price=Math.round(Number(f.get('price'))*1000);const pack=Number(f.get('pack'));if(!title||!Number.isFinite(price)||price<0||!Number.isInteger(pack)||pack<1||pack>100)throw Error('Enter a title, valid price and pack size.');await db().prepare('INSERT INTO events VALUES (?,?,?,?,?,?)').bind(id,title,String(f.get('date')),String(f.get('location')),price,pack).run();}
else if(action==='member'&&owner){const email=String(f.get('email')).trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw Error('Enter a valid email.');await db().prepare('INSERT OR IGNORE INTO members VALUES (?)').bind(email).run();}
else if(action==='remove-member'&&owner){await db().prepare('DELETE FROM members WHERE email=?').bind(String(f.get('email'))).run();}
else if(action==='upload'&&contributor){const event=String(f.get('event'));if(!await db().prepare('SELECT id FROM events WHERE id=?').bind(event).first())throw Error('Choose an event.');const original=f.get('original') as File;const preview=f.get('preview') as File;if(!original||!preview||!['image/jpeg','image/png','image/webp'].includes(original.type)||preview.type!=='image/jpeg'||original.size>20*1024*1024||preview.size>2*1024*1024)throw Error('Use JPG, PNG or WebP, up to 20 MB.');const key='original/'+id;const pk='preview/'+id;await bucket().put(key,await original.arrayBuffer(),{httpMetadata:{contentType:original.type}});await bucket().put(pk,await preview.arrayBuffer(),{httpMetadata:{contentType:'image/jpeg'}});await db().prepare('INSERT INTO photos VALUES (?,?,?,?,?,?)').bind(id,event,String(f.get('label')||original.name),key,pk,user.userId).run();}
else if(action==='order'){const event=String(f.get('event'));const ev=await db().prepare('SELECT * FROM events WHERE id=?').bind(event).first<any>();const selected=JSON.parse(String(f.get('photos')));if(!ev||!Array.isArray(selected)||selected.length!==ev.pack||new Set(selected).size!==selected.length)throw Error('Select the exact number of photos in this pack.');for(const p of selected){if(!await db().prepare('SELECT id FROM photos WHERE id=? AND event=?').bind(p,event).first())throw Error('Invalid photo selection.');}await db().prepare('INSERT INTO orders VALUES (?,?,?,?,?,?,?,?)').bind(id,user.userId,user.email,event,JSON.stringify(selected),ev.price,'pending',new Date().toISOString()).run();}
else if(action==='approve'&&owner){await db().prepare("UPDATE orders SET status='paid' WHERE id=?").bind(String(f.get('id'))).run();}
else return Response.json({error:'You do not have access to this action.'},{status:403});return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'Could not save. Try again.'},{status:400});}}
